server:
  port: 8888
  servlet:
    context-path: /sanye   #统一访问的前缀
spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 0
    timeout: 1000
captcha:
  width: 133
  height: 40