#服务端配置
server:
  port: 8888
  servlet:
    context-path: /sanye   #统一请求前缀

spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 0
    timeout: 1000
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sanye}?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 180000
      connection-test-query: select 1
#自定义的验证码配置
captcha:
  width: 133
  height: 40
  expire: 300
  size: 2
#自定义是否开启swagger2文档
swagger:
  enable:true
#springboot自带的logback配置
logging:
  file:
    path: /app/log
  level:
    root: info
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false #https://zhuanlan.zhihu.com/p/344988816 mybatis-plus默认将下划线转驼峰，导致实体封装会有问题，关闭就行，否则每次都要指定resultMap
# JWT配置
jwt:
  # 密匙Key
  secret: sanyeSecurity
  # HeaderKey
  tokenHeader: Authorization
  # Token前缀
  tokenPrefix: Bearer
  # 过期时间，单位秒
  expiration: 604800
  # 配置白名单（不需要认证）
  antMatchers: /,/login/**,/register/**,/static/**,/index.html,/swagger-resources/**,/webjars/**,/v2/api-docs,/captcha,/user/test