#服务端配置
server:
  port: 8888 #端口
  servlet:
    context-path: /sanye   #统一请求前缀
spring:
  redis:    #redis链接配置
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 0
    timeout: 1000
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sanye}?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 180000
      connection-test-query: select 1
captcha: #自定义的验证码配置
  width: 133
  height: 40
  expire: 60*3
  size: 3
swagger: #自定义是否开启swagger2文档
  enable:true
logging: #springboot自带的logback配置
  file:
    path: /app/log
  level:
    root: info
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
